### ISSUE TITLE
Serviço para compartilhar mensagens secretas

### ISSUE THREAD

**Issue by jonatasbaldin** [manualdousuario/pcdomanual-infra#1]
Oi gente, tudo bem?

Eu e o @rghedin converamos sobre instalar um serviço de compartilhamento de mensagens secretas, como o [OneTimeSecret](https://onetimesecret.com/).

Eu já usei o [OTS](https://ots.fyi/) uma vez e gostei bastante. Mas vi que há algumas outras opcões, como o [shhh](https://github.com/smallwat3r/shhh), [Yopass](https://yopass.se).

O que acham? Se souberem outras soluções também, podem mandar!

Abraços!

**Comment by gil** [comment]
Parece interessante mas não sei se é algo que eu usaria, não me lembro de sentir necessidade, talvez por desconhecer.

A única coisa que eu pensaria é sobre permitir que pessoas armazenem qualquer conteúdo no seu servidor sem a possibilidade de moderar. Mas como é só texto, encriptado e temporário, talvez não seja uma grande preocupação.

**Comment by rghedin** [comment]
@gil, a gente usa no **Manual** para compartilhar senhas. Em vez de colar num aplicativo ou coisa do tipo, usamos o [OnceOn.ly](https://onceon.ly) e mandamos o link para a pessoa abrir, salvar a senha e boa.

Dito isso, creio que a utilidade seja limitada mesmo, mas, talvez, com o serviço oferecido e a publicidade dele no PC do Manual/**Manual do Usuário**, mais gente passe a usar…?

**Comment by aaadonai** [comment]
Já usei serviços como este e eles parecem ser de baixa manutenção e usar pouco recursos. Diferente de um miniflux por exemplo.
Se tivesse um serviço destes no pc do manual, acredito que voltaria a usar. Hoje acabo mandando este tipo de informação de forma aberta e apagando depois, o que não é ideal.

**Comment by rsilvr** [comment]
Ao contrário do Linkding e do Miniflux, essa é uma funcionalidade que para mim hoje não é atendida por nenhum serviço. Se rolar, com certeza vai estar no meu favoritos do navegador.
Uma outra sugestão na mesma pegada (vale um novo issue?) seria um serviço para envio de arquivos, no qual hoje eu utilizo o copypaste.me, mas ficaria bem interessado em uma solução hospedada pelo Manual.

**Comment by rghedin** [comment]
Não conhecia esse copypaste.me, @rsilvr. Parece legal! Similar ao OTS que o @jonatasbaldin sugeriu. Gosto desses porque aceitam pequenos arquivos. Creio que se limitarmos o tamanho máximo, não teremos problemas com abusos.

Seria só o caso de sentar e decidir qual dos dois projetos adotar. Dando uma olhada nos repositórios, o OTS parece mais ativo e pronto para deploy. O que acha, @jonatasbaldin?

**Comment by jonatasbaldin** [comment]
Legal gente! Vou fazer o deploy do OTS, acho que é o mais ativo e completo hoje.

**Comment by jonatasbaldin** [comment]
https://segredo.pcdomanual.com

shhh!
